name: hexlet-ci-app
# on – определяет события, которые запускают воркфлоу
on: push

# Пример для проекта на Node.js
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
      uses: actions/setup-node@master
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run lint
      - name: run tests
        run: npm test
      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_KEY_SECRET }}  
